"""
This module defines Pydantic models used for client-related API requests and data validation.
"""
from pydantic import BaseModel


class PredictionInput(BaseModel):
    """
    Represents the input schema for client prediction requests.
    Includes demographic, work, and personal data for validation.
    """
    age: int
    gender: str
    work_experience: int
    canada_workex: int
    dep_num: int
    canada_born: str
    citizen_status: str
    level_of_schooling: str
    fluent_english: str
    reading_english_scale: int
    speaking_english_scale: int
    writing_english_scale: int
    numeracy_scale: int
    computer_scale: int
    transportation_bool: str
    caregiver_bool: str
    housing: str
    income_source: str
    felony_bool: str
    attending_school: str
    currently_employed: str
    substance_use: str
    time_unemployed: int
    need_mental_health_support_bool: str
    # pylint: disable=duplicate-code


class ClientData(BaseModel):
    """
    Represents the schema for client data with various attributes.
    """
    id: str = None  # Auto-generated by the system
    name: str
    email: str
    age: int
    gender: str
